-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.backup_auth_users (
  instance_id uuid,
  id uuid,
  aud character varying,
  role character varying,
  email character varying,
  encrypted_password character varying,
  email_confirmed_at timestamp with time zone,
  invited_at timestamp with time zone,
  confirmation_token character varying,
  confirmation_sent_at timestamp with time zone,
  recovery_token character varying,
  recovery_sent_at timestamp with time zone,
  email_change_token_new character varying,
  email_change character varying,
  email_change_sent_at timestamp with time zone,
  last_sign_in_at timestamp with time zone,
  raw_app_meta_data jsonb,
  raw_user_meta_data jsonb,
  is_super_admin boolean,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  phone text,
  phone_confirmed_at timestamp with time zone,
  phone_change text,
  phone_change_token character varying,
  phone_change_sent_at timestamp with time zone,
  confirmed_at timestamp with time zone,
  email_change_token_current character varying,
  email_change_confirm_status smallint,
  banned_until timestamp with time zone,
  reauthentication_token character varying,
  reauthentication_sent_at timestamp with time zone,
  is_sso_user boolean,
  deleted_at timestamp with time zone,
  is_anonymous boolean
);
CREATE TABLE public.backup_products (
  id uuid,
  seller_id uuid,
  category_id uuid,
  name character varying,
  description text,
  thumbnail_url text,
  images jsonb,
  starting_price numeric,
  step_price numeric,
  buy_now_price numeric,
  current_price numeric,
  auto_extend boolean,
  auto_extend_minutes integer,
  auto_extend_threshold integer,
  allow_unrated_bidders boolean,
  start_time timestamp with time zone,
  end_time timestamp with time zone,
  status USER-DEFINED,
  rejected_reason text,
  winner_id uuid,
  final_price numeric,
  bid_count integer,
  view_count integer,
  watchlist_count integer,
  created_at timestamp with time zone,
  updated_at timestamp with time zone,
  search_vector tsvector
);
CREATE TABLE public.backup_profiles (
  id uuid,
  email character varying,
  full_name character varying,
  role USER-DEFINED,
  date_of_birth date,
  address text,
  phone character varying,
  avatar_url text,
  rating_positive integer,
  rating_negative integer,
  is_banned boolean,
  banned_reason text,
  banned_at timestamp with time zone,
  created_at timestamp with time zone,
  updated_at timestamp with time zone
);
CREATE TABLE public.bids (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  bidder_id uuid NOT NULL,
  bid_amount numeric NOT NULL CHECK (bid_amount > 0::numeric),
  max_bid_amount numeric,
  is_auto_bid boolean DEFAULT false,
  is_rejected boolean DEFAULT false,
  rejected_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT bids_pkey PRIMARY KEY (id),
  CONSTRAINT bids_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT bids_bidder_id_fkey FOREIGN KEY (bidder_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.categories (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  description text,
  parent_id uuid,
  icon character varying,
  display_order integer DEFAULT 0,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT categories_pkey PRIMARY KEY (id),
  CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.categories(id)
);
CREATE TABLE public.order_chat (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  order_id uuid NOT NULL,
  sender_id uuid NOT NULL,
  message text NOT NULL,
  attachment_url text,
  is_read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT order_chat_pkey PRIMARY KEY (id),
  CONSTRAINT order_chat_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id),
  CONSTRAINT order_chat_sender_id_fkey FOREIGN KEY (sender_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  seller_id uuid NOT NULL,
  buyer_id uuid NOT NULL,
  final_price numeric NOT NULL,
  shipping_address text,
  shipping_tracking_number character varying,
  payment_proof_url text,
  payment_confirmed_at timestamp with time zone,
  status USER-DEFINED DEFAULT 'pending_payment'::order_status,
  shipped_at timestamp with time zone,
  delivered_at timestamp with time zone,
  cancelled_by uuid,
  cancelled_at timestamp with time zone,
  cancellation_reason text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT orders_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.profiles(id),
  CONSTRAINT orders_buyer_id_fkey FOREIGN KEY (buyer_id) REFERENCES public.profiles(id),
  CONSTRAINT orders_cancelled_by_fkey FOREIGN KEY (cancelled_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.otp_codes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  email character varying NOT NULL,
  otp_code character varying NOT NULL CHECK (length(otp_code::text) = 6),
  purpose character varying NOT NULL DEFAULT 'email_verification'::character varying,
  is_verified boolean DEFAULT false,
  verified_at timestamp with time zone,
  expires_at timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  ip_address character varying,
  user_agent text,
  CONSTRAINT otp_codes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.product_descriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  description text NOT NULL,
  added_at timestamp with time zone DEFAULT now(),
  CONSTRAINT product_descriptions_pkey PRIMARY KEY (id),
  CONSTRAINT product_descriptions_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  seller_id uuid NOT NULL,
  category_id uuid NOT NULL,
  name character varying NOT NULL,
  description text NOT NULL,
  thumbnail_url text NOT NULL,
  images jsonb DEFAULT '[]'::jsonb,
  starting_price numeric NOT NULL CHECK (starting_price >= 0::numeric),
  step_price numeric NOT NULL CHECK (step_price > 0::numeric),
  buy_now_price numeric,
  current_price numeric DEFAULT 0,
  auto_extend boolean DEFAULT false,
  auto_extend_minutes integer DEFAULT 10,
  auto_extend_threshold integer DEFAULT 5,
  allow_unrated_bidders boolean DEFAULT true,
  start_time timestamp with time zone DEFAULT now(),
  end_time timestamp with time zone NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::product_status,
  rejected_reason text,
  winner_id uuid,
  final_price numeric,
  bid_count integer DEFAULT 0,
  view_count integer DEFAULT 0,
  watchlist_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  search_vector tsvector,
  CONSTRAINT products_pkey PRIMARY KEY (id),
  CONSTRAINT products_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.profiles(id),
  CONSTRAINT products_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(id),
  CONSTRAINT products_winner_id_fkey FOREIGN KEY (winner_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email character varying NOT NULL UNIQUE,
  full_name character varying NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'bidder'::user_role,
  date_of_birth date,
  address text,
  phone character varying,
  avatar_url text,
  rating_positive integer DEFAULT 0,
  rating_negative integer DEFAULT 0,
  is_banned boolean DEFAULT false,
  banned_reason text,
  banned_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.questions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  asker_id uuid NOT NULL,
  question text NOT NULL,
  answer text,
  answered_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT questions_pkey PRIMARY KEY (id),
  CONSTRAINT questions_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT questions_asker_id_fkey FOREIGN KEY (asker_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.ratings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  from_user_id uuid NOT NULL,
  to_user_id uuid NOT NULL,
  product_id uuid,
  rating USER-DEFINED NOT NULL,
  comment text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT ratings_pkey PRIMARY KEY (id),
  CONSTRAINT ratings_from_user_id_fkey FOREIGN KEY (from_user_id) REFERENCES public.profiles(id),
  CONSTRAINT ratings_to_user_id_fkey FOREIGN KEY (to_user_id) REFERENCES public.profiles(id),
  CONSTRAINT fk_ratings_product FOREIGN KEY (product_id) REFERENCES public.products(id)
);
CREATE TABLE public.rejected_bidders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid NOT NULL,
  bidder_id uuid NOT NULL,
  seller_id uuid NOT NULL,
  reason text,
  rejected_at timestamp with time zone DEFAULT now(),
  CONSTRAINT rejected_bidders_pkey PRIMARY KEY (id),
  CONSTRAINT rejected_bidders_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id),
  CONSTRAINT rejected_bidders_bidder_id_fkey FOREIGN KEY (bidder_id) REFERENCES public.profiles(id),
  CONSTRAINT rejected_bidders_seller_id_fkey FOREIGN KEY (seller_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.spam_reports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  reporter_id uuid NOT NULL,
  reported_user_id uuid NOT NULL,
  report_type USER-DEFINED NOT NULL DEFAULT 'user'::spam_report_type,
  reported_product_id uuid,
  reported_bid_id uuid,
  reason text NOT NULL,
  evidence_urls ARRAY,
  status USER-DEFINED DEFAULT 'pending'::spam_report_status,
  action_taken character varying,
  admin_note text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT spam_reports_pkey PRIMARY KEY (id),
  CONSTRAINT spam_reports_reporter_id_fkey FOREIGN KEY (reporter_id) REFERENCES public.profiles(id),
  CONSTRAINT spam_reports_reported_user_id_fkey FOREIGN KEY (reported_user_id) REFERENCES public.profiles(id),
  CONSTRAINT spam_reports_reported_product_id_fkey FOREIGN KEY (reported_product_id) REFERENCES public.products(id),
  CONSTRAINT spam_reports_reported_bid_id_fkey FOREIGN KEY (reported_bid_id) REFERENCES public.bids(id),
  CONSTRAINT spam_reports_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.system_settings (
  key character varying NOT NULL,
  value text NOT NULL,
  description text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT system_settings_pkey PRIMARY KEY (key)
);
CREATE TABLE public.upgrade_requests (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::upgrade_request_status,
  reason text,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  admin_note text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT upgrade_requests_pkey PRIMARY KEY (id),
  CONSTRAINT upgrade_requests_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT upgrade_requests_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES public.profiles(id)
);
CREATE TABLE public.watchlist (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  product_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT watchlist_pkey PRIMARY KEY (id),
  CONSTRAINT watchlist_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT watchlist_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.products(id)
);